### ISSUE TITLE
Publish v1 on npm

### ISSUE THREAD

**Issue by KoryNunn** [medikoo/es6-map#4]
Can this module be published as version 1 on npm so that it can be updated via `npm up`

**Comment by medikoo** [comment]
Version v1 will be published at some point, but If I [read](https://www.npmjs.com/package/npm-up) correctly`0.x` versions also should work with `npm up` as expected (?)

**Comment by KoryNunn** [comment]
It has issues: https://github.com/npm/node-semver/issues/79

**Comment by medikoo** [comment]
@KoryNunn the issue you mention, probably refers only to `0.0.x` versions, while es6-map is at `0.x.x` currently, and that should work without issues. See https://github.com/npm/node-semver/pull/41#issuecomment-21354034

**Comment by KoryNunn** [comment]
If that is how it works, it's still probably a good idea to put it to 1 as soon as possible, assuming reasonable stability and completion, otherwise people who are using your module will no longer get the latest version at an arbitrary point because you updated to 1.

This exact issue happened to me with your weak-map module, which I installed before v1 was released. I nearly submitted a duplicate of #2 because I didn't get v1 through npm up

**Comment by medikoo** [comment]
It's very good that `npm up` won't switch from `0.x` to  `1.0`, otherwise it'll be a critical bug in `npm up`.

At this point I don't see any issue, switch between `0.1` and `1.0` should be considered as breaking and no tool should do it automatically. That's expected behavior, and `npm up` works perfectly for current es6-map versions e.g. if I release non breaking `0.1.2` update, npm up will update it for you.

**Comment by QuantumInformation** [comment]
Is there a minified version I can just copy paste, I don't want to use a build system
